"""Shared constants for the Pong game."""
WIDTH, HEIGHT = 480, 320
PADDLE_H = 60
PADDLE_W = 10
BALL_SIZE = 8
PADDLE_SPEED = 4.0
AI_SPEED = 3.0
BALL_SPEED = 3.5
BALL_SPEED_MAX = 2.5 * BALL_SPEED
BALL_VY_MAX = 6.0
AI_REACTION_FRAMES = 8
AI_ERROR_SIGMA = 12.0
AI_MISS_PROB = 0.10
AI_CURRICULUM_STEP = 0.05
AI_MIN_SPEED_FACTOR = 0.5
AI_MAX_SIGMA_FACTOR = 1.0
AI_MIN_SIGMA_FACTOR = 0.3
